name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true
        default: '1.0.0'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Cache Maven packages
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    
    - name: Build JAR with Maven
      run: |
        cd TicTacToe
        mvn clean compile package -DskipTests
        ls -la target/
    
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Tic Tac Toe Game ${{ github.ref_name }}
        body: |
          ## 🎮 Tic Tac Toe Game ${{ github.ref_name }}
          
          A cross-platform Tic Tac Toe game with intelligent AI opponent.
          
          ### 📦 Download
          
          **Cross-platform JAR file** (requires Java 17+):
          - Download `TicTacToe-1.0.0.jar`
          - Run with: `java -jar TicTacToe-1.0.0.jar`
          
          ### ✨ Features
          - 🎯 Player vs Player and Player vs Computer modes
          - 🧠 Smart AI using Minimax algorithm
          - 📊 Score tracking
          - 🔄 Game reset and mode switching
          - 🎨 Clean, intuitive Swing interface
          
          ### 🚀 How to Run
          1. Make sure you have Java 17+ installed
          2. Download the JAR file
          3. Double-click the JAR file or run: `java -jar TicTacToe-1.0.0.jar`
        draft: false
        prerelease: false
    
    - name: Upload JAR to Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./TicTacToe/target/TicTacToe-1.0.0.jar
        asset_name: TicTacToe-1.0.0.jar
        asset_content_type: application/java-archive