name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true
        default: '1.0.0'

jobs:
  build-jar:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    
    - name: Build with Maven
      run: |
        cd TicTacToe
        mvn clean package -DskipTests
    
    - name: Upload JAR artifact
      uses: actions/upload-artifact@v3
      with:
        name: tictactoe-jar
        path: TicTacToe/target/TicTacToe-*.jar

  build-windows:
    runs-on: windows-latest
    needs: build-jar
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    
    - name: Build JAR
      run: |
        cd TicTacToe
        mvn clean package -DskipTests
    
    - name: Create Windows Executable
      run: |
        cd TicTacToe
        mvn package -P windows -DskipTests
    
    - name: Upload Windows artifacts
      uses: actions/upload-artifact@v3
      with:
        name: tictactoe-windows
        path: |
          TicTacToe/target/TicTacToe-*.exe
          TicTacToe/target/dist/

  build-linux:
    runs-on: ubuntu-latest
    needs: build-jar
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    
    - name: Build JAR
      run: |
        cd TicTacToe
        mvn clean package -DskipTests
    
    - name: Create Linux AppImage
      run: |
        cd TicTacToe
        mvn package -P linux -DskipTests
    
    - name: Upload Linux artifacts
      uses: actions/upload-artifact@v3
      with:
        name: tictactoe-linux
        path: TicTacToe/target/dist/

  build-macos:
    runs-on: macos-latest
    needs: build-jar
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    
    - name: Build JAR
      run: |
        cd TicTacToe
        mvn clean package -DskipTests
    
    - name: Create macOS app bundle
      run: |
        cd TicTacToe
        jpackage --input target --name TicTacToe --main-jar TicTacToe-1.0.0.jar --main-class com.example.TicTacToeSwing --type app-image --dest target/dist
    
    - name: Upload macOS artifacts
      uses: actions/upload-artifact@v3
      with:
        name: tictactoe-macos
        path: TicTacToe/target/dist/

  create-release:
    runs-on: ubuntu-latest
    needs: [build-jar, build-windows, build-linux, build-macos]
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Download all artifacts
      uses: actions/download-artifact@v3
    
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          ## Tic Tac Toe Game Release
          
          ### Downloads
          - **Windows**: Download the `.exe` file for Windows
          - **Linux**: Download the AppImage for Linux
          - **macOS**: Download the `.app` bundle for macOS
          - **Cross-platform**: Download the `.jar` file (requires Java 17+)
          
          ### Changes
          - GUI-based Tic Tac Toe game
          - Player vs Player and Player vs Computer modes
          - Score tracking
          - Minimax algorithm for computer AI
        draft: false
        prerelease: false
    
    - name: Upload JAR Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./tictactoe-jar/TicTacToe-1.0.0.jar
        asset_name: TicTacToe-1.0.0.jar
        asset_content_type: application/java-archive
    
    - name: Upload Windows EXE Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./tictactoe-windows/TicTacToe-1.0.0.exe
        asset_name: TicTacToe-1.0.0-Windows.exe
        asset_content_type: application/octet-stream